# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cbb15b5d6ec32d3bdb64de279560436ef0e286b850b7cd4e7f3a345128ddfc1181f5ff2f7496e10d1e54a75ff65f6ed78a7bbb9637afe70d765ee05f267eb2d

test:
  secret_key_base: 5d175ba637f8e0dbc71bb7699eb89e1e5030c17fd55d024b713684a8e63e854e04518fac858ead4e3387dea4ced991534d0aa39efc63fe645c8181fba84a2524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
